pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        bat 'javac JenkinsExample.java'
      }
    }

    stage('Run') {
      steps {
        bat 'java JenkinsExample'
      }
    }
  }
}
